CREATE DATABASE IF NOT EXISTS Hello;

USE Hello;

CREATE TABLE IF NOT EXISTS ExecutionJob (
  id VARCHAR(50) PRIMARY KEY,
  sessionId VARCHAR(50) NOT NULL,
  filePath VARCHAR(200) NOT NULL,
  createdAt DATETIME(3) NOT NULL,
  output TEXT NULL,
  error TEXT NULL,
  exitCode INT NULL,
  completedAt DATETIME(3) NULL
);

CREATE TABLE IF NOT EXISTS ExecutionJobStatusLog (
  id VARCHAR(50) PRIMARY KEY,
  jobId VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  createdAt DATETIME(3) NOT NULL,
  CONSTRAINT fk_job FOREIGN KEY (jobId) REFERENCES ExecutionJob(id) ON DELETE CASCADE
);
